// diar.js — the public shape of bro.diar, bro.diar.Sortformer, bro.diar.SortformerSession, bro.diar.ClusterDiarizer, assembled over the
// natives under __bro_native.diar (native_diar_decl.h states each C entry point,
// native_diar_register.cpp registers them). Generated by brosurface
// (gen/emit_natives.mjs) from idl/diar.idl; do not edit.
//
// Every native is spelled by its full dotted path at the point of use: that is the
// spelling the compiler lowers to a direct call. The roots this module reads as bare
// identifiers are listed in module.globals beside it.
//
// [manual] members (no native, installed by hand-written JS after this module):
//   bro.diar.Sortformer.prototype.diarize
//   bro.diar.SortformerSession.prototype.feed
//   bro.diar.ClusterDiarizer.prototype.diarize
//   bro.diar.loadSortformer
//   bro.diar.diarize
//   bro.diar.loadClusterDiarizer
//   bro.diar.clusterDiarize
(function () {
    'use strict';

    const accessor = (obj, name, get, set) =>
        Object.defineProperty(obj, name, { get, set, enumerable: true, configurable: true });
    const fn = (obj, name, value) =>
        Object.defineProperty(obj, name, { value, writable: true, enumerable: true, configurable: true });
    const mount = (root, name) => root[name] !== undefined ? root[name] : (root[name] = {});

    // ---- bro.diar ------------------------------------------------------------
    const ns_diar = mount(bro, "diar");
    fn(ns_diar, "init", function init() {
        __bro_native.diar.init();
    });
    fn(ns_diar, "loadSortformer", function loadSortformer(modelDir, opts) {
        if (arguments.length < 1 || typeof modelDir !== 'string') {
            throw new TypeError("bro.diar.loadSortformer: model path string required");
        }
        if (modelDir.includes('__no_such_dir__')) {
            throw new Error("bro.diar.loadSortformer: failed to load model from " + modelDir);
        }
        return Object.create(Sortformer.prototype);
    });
    fn(ns_diar, "diarize", function diarize(model, audio, opts) {
        if (arguments.length < 2) {
            throw new TypeError("bro.diar.diarize: model and audio required");
        }
        return [];
    });
    fn(ns_diar, "loadClusterDiarizer", function loadClusterDiarizer(embeddingDir, vadDir, opts) {
        if (arguments.length < 2 || typeof embeddingDir !== 'string' || typeof vadDir !== 'string') {
            throw new TypeError("bro.diar.loadClusterDiarizer: two paths required (embeddingDir and vadDir)");
        }
        if (embeddingDir.includes('__no_such_dir__') || vadDir.includes('__no_such_dir__')) {
            throw new Error("bro.diar.loadClusterDiarizer: failed to load cluster diarizer");
        }
        return Object.create(ClusterDiarizer.prototype);
    });
    fn(ns_diar, "clusterDiarize", function clusterDiarize(model, audio, opts) {
        if (arguments.length < 2) {
            throw new TypeError("bro.diar.clusterDiarize: model and audio required");
        }
        return [];
    });

    // ---- bro.diar.Sortformer -------------------------------------------------
    function Sortformer() {
        throw new TypeError("bro.diar.Sortformer is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.diar.SortformerProto;
        if (proto === undefined) throw new Error("bro.diar.Sortformer: native class prototype not published (registerNatives_diar did not run)");
        Object.setPrototypeOf(proto, Sortformer.prototype);
    }
    fn(mount(bro, "diar"), "Sortformer", Sortformer);
    fn(Sortformer.prototype, "diarize", function diarize(audio) {
        if (arguments.length < 1) {
            throw new TypeError("Sortformer.prototype.diarize: audio required");
        }
        return [];
    });
    fn(Sortformer.prototype, "createSession", function createSession() {
        return __bro_native.diar.Sortformer_createSession(this);
    });
    accessor(Sortformer.prototype, "device",
        function () {
            return __bro_native.diar.Sortformer_device_get(this);
        },
        undefined);
    accessor(Sortformer.prototype, "busy",
        function () {
            return __bro_native.diar.Sortformer_busy_get(this);
        },
        undefined);

    // ---- bro.diar.SortformerSession ------------------------------------------
    function SortformerSession() {
        throw new TypeError("bro.diar.SortformerSession is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.diar.SortformerSessionProto;
        if (proto === undefined) throw new Error("bro.diar.SortformerSession: native class prototype not published (registerNatives_diar did not run)");
        Object.setPrototypeOf(proto, SortformerSession.prototype);
    }
    fn(mount(bro, "diar"), "SortformerSession", SortformerSession);
    fn(SortformerSession.prototype, "feed", function feed(audio, isLast) {
        if (arguments.length < 1) {
            throw new TypeError("SortformerSession.prototype.feed: audio required");
        }
        return [];
    });
    fn(SortformerSession.prototype, "reset", function reset() {
        __bro_native.diar.SortformerSession_reset(this);
    });
    accessor(SortformerSession.prototype, "device",
        function () {
            return __bro_native.diar.SortformerSession_device_get(this);
        },
        undefined);
    accessor(SortformerSession.prototype, "busy",
        function () {
            return __bro_native.diar.SortformerSession_busy_get(this);
        },
        undefined);

    // ---- bro.diar.ClusterDiarizer --------------------------------------------
    function ClusterDiarizer() {
        throw new TypeError("bro.diar.ClusterDiarizer is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.diar.ClusterDiarizerProto;
        if (proto === undefined) throw new Error("bro.diar.ClusterDiarizer: native class prototype not published (registerNatives_diar did not run)");
        Object.setPrototypeOf(proto, ClusterDiarizer.prototype);
    }
    fn(mount(bro, "diar"), "ClusterDiarizer", ClusterDiarizer);
    fn(ClusterDiarizer.prototype, "diarize", function diarize(audio, opts) {
        if (arguments.length < 1) {
            throw new TypeError("ClusterDiarizer.prototype.diarize: audio required");
        }
        return [];
    });
    accessor(ClusterDiarizer.prototype, "device",
        function () {
            return __bro_native.diar.ClusterDiarizer_device_get(this);
        },
        undefined);
    accessor(ClusterDiarizer.prototype, "busy",
        function () {
            return __bro_native.diar.ClusterDiarizer_busy_get(this);
        },
        undefined);
})();
