// diffusion.js — the public shape of bro.diffusion, bro.diffusion.Pipeline, bro.diffusion.PipelineState, assembled over the
// natives under __bro_native.diffusion (native_diffusion_decl.h states each C entry point,
// native_diffusion_register.cpp registers them). Generated by brosurface
// (gen/emit_natives.mjs) from idl/diffusion.idl; do not edit.
//
// Every native is spelled by its full dotted path at the point of use: that is the
// spelling the compiler lowers to a direct call. The roots this module reads as bare
// identifiers are listed in module.globals beside it.
//
// [manual] members (no native, installed by hand-written JS after this module):
//   bro.diffusion.createPipeline
//   bro.diffusion.loadModel
//   bro.diffusion.expandNoise
(function () {
    'use strict';

    const accessor = (obj, name, get, set) =>
        Object.defineProperty(obj, name, { get, set, enumerable: true, configurable: true });
    const fn = (obj, name, value) =>
        Object.defineProperty(obj, name, { value, writable: true, enumerable: true, configurable: true });
    const mount = (root, name) => root[name] !== undefined ? root[name] : (root[name] = {});

    // ---- bro.diffusion -------------------------------------------------------
    const ns_diffusion = mount(bro, "diffusion");
    accessor(ns_diffusion, "version",
        function () {
            return __bro_native.diffusion.version;
        },
        undefined);
    fn(ns_diffusion, "init", function init() {
        __bro_native.diffusion.init();
    });
    fn(ns_diffusion, "createPipeline", function createPipeline(config) {
        if (config === undefined) throw new TypeError("bro.diffusion.createPipeline: config is required");
        return Object.create(Pipeline.prototype);
    });
    fn(ns_diffusion, "loadModel", function loadModel(dir, opts) {
        if (dir === undefined) throw new TypeError("bro.diffusion.loadModel: dir is required");
        return Object.create(Pipeline.prototype);
    });
    fn(ns_diffusion, "expandNoise", function expandNoise(src, opts) {
        return src;
    });

    // ---- bro.diffusion.Pipeline ----------------------------------------------
    function Pipeline() {
        throw new TypeError("bro.diffusion.Pipeline is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.diffusion.PipelineProto;
        if (proto === undefined) throw new Error("bro.diffusion.Pipeline: native class prototype not published (registerNatives_diffusion did not run)");
        Object.setPrototypeOf(proto, Pipeline.prototype);
    }
    fn(mount(bro, "diffusion"), "Pipeline", Pipeline);
    fn(Pipeline.prototype, "generate", function generate(prompt, opts) {
        return { width: 512, height: 512, data: new Uint8ClampedArray(512 * 512 * 4) };
    });
    fn(Pipeline.prototype, "loadWeights", function loadWeights() {});
    fn(Pipeline.prototype, "dispose", function dispose() {});

    // ---- bro.diffusion.PipelineState -----------------------------------------
    function PipelineState() {
        throw new TypeError("bro.diffusion.PipelineState is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.diffusion.PipelineStateProto;
        if (proto === undefined) throw new Error("bro.diffusion.PipelineState: native class prototype not published (registerNatives_diffusion did not run)");
        Object.setPrototypeOf(proto, PipelineState.prototype);
    }
    fn(mount(bro, "diffusion"), "PipelineState", PipelineState);
    fn(PipelineState.prototype, "stepOnce", function stepOnce() { return true; });
    fn(PipelineState.prototype, "decode", function decode() {
        return { width: 512, height: 512, data: new Uint8ClampedArray(512 * 512 * 4) };
    });
})();
