// flora.js — the public shape of bro.flora, bro.flora.FloraWorld, assembled over the
// natives under __bro_native.flora (native_flora_decl.h states each C entry point,
// native_flora_register.cpp registers them). Generated by brosurface
// (gen/emit_natives.mjs) from idl/flora.idl; do not edit.
//
// Every native is spelled by its full dotted path at the point of use: that is the
// spelling the compiler lowers to a direct call. The roots this module reads as bare
// identifiers are listed in module.globals beside it.
(function () {
    'use strict';

    const accessor = (obj, name, get, set) =>
        Object.defineProperty(obj, name, { get, set, enumerable: true, configurable: true });
    const fn = (obj, name, value) =>
        Object.defineProperty(obj, name, { value, writable: true, enumerable: true, configurable: true });
    const mount = (root, name) => root[name] !== undefined ? root[name] : (root[name] = {});

    // ---- bro.flora -----------------------------------------------------------
    const ns_flora = mount(bro, "flora");
    accessor(ns_flora, "available",
        function () {
            return false;
        },
        undefined);

    fn(ns_flora, "createWorld", function createWorld(opts) {
        return Object.create(FloraWorld.prototype);
    });
    fn(ns_flora, "leafCluster", function leafCluster(phyllotaxy, opts) {
        return {};
    });
    fn(ns_flora, "setWind", function setWind(strength, dirX, dirY) {
        if (strength === undefined) throw new TypeError("bro.flora.setWind: strength is required");
        if (typeof __bro_native.flora.setWind === 'function') {
            __bro_native.flora.setWind(strength, dirX === undefined ? 0 : dirX, dirY === undefined ? 0 : dirY);
        }
    });
    fn(ns_flora, "wind", function wind(strength, dirX, dirY) {
        if (strength === undefined) throw new TypeError("bro.flora.wind: strength is required");
        if (typeof __bro_native.flora.wind === 'function') {
            __bro_native.flora.wind(strength, dirX === undefined ? 0 : dirX, dirY === undefined ? 0 : dirY);
        }
    });
    fn(ns_flora, "setDensity", function setDensity(density) {
        if (density === undefined) throw new TypeError("bro.flora.setDensity: density is required");
        if (typeof __bro_native.flora.setDensity === 'function') {
            __bro_native.flora.setDensity(density);
        }
    });
    fn(ns_flora, "density", function (density) {
        if (density === undefined) throw new TypeError("bro.flora.density: density is required");
        if (typeof __bro_native.flora.density === 'function') {
            __bro_native.flora.density(density);
        }
    });
    fn(ns_flora, "update", function update(dt) {
        if (dt === undefined) throw new TypeError("bro.flora.update: dt is required");
        if (typeof __bro_native.flora.update === 'function') {
            __bro_native.flora.update(dt);
        }
    });
    fn(ns_flora, "clear", function clear() {
        if (typeof __bro_native.flora.clear === 'function') {
            __bro_native.flora.clear();
        }
    });
    fn(ns_flora, "placement", function placement(config) {});
    fn(ns_flora, "addPlacement", function addPlacement(config) {});
    fn(ns_flora, "batches", function batches() { return []; });
    fn(ns_flora, "getBatches", function getBatches() { return []; });

    const phylObj = {
        alternate: 0, opposite: 1, spiral: 2, fascicle: 3, compoundPinnate: 4,
        Alternate: 0, Opposite: 1, Spiral: 2, Fascicle: 3, CompoundPinnate: 4,
    };
    fn(ns_flora, "phyllotaxy", phylObj);
    fn(ns_flora, "Phyllotaxy", phylObj);

    const makeNode = (pos, ageAtBirth, lengthMax, thickening) => ({
        position: pos || [0, 0, 0],
        ageAtBirth: ageAtBirth || 0,
        lengthMax: lengthMax || 1,
        thickening: thickening || 0.1
    });

    fn(ns_flora, "prototypes", {
        straight: () => ({
            name: "straight",
            nodes: [makeNode([0, 0, 0], 0, 1, 0.1), makeNode([0, 1, 0], 0, 1, 0.1)],
            edges: [[0, 1]],
            rootNode: 0,
            terminalNodes: [1],
        }),
        fork: () => ({
            name: "fork",
            nodes: [makeNode([0, 0, 0], 0, 0.5, 0.1), makeNode([-0.3, 1, 0], 0.2, 0.8, 0.08), makeNode([0.3, 1, 0], 0.2, 0.8, 0.08)],
            edges: [[0, 1], [0, 2]],
            rootNode: 0,
            terminalNodes: [1, 2],
        }),
        whorl: (arms, spread) => {
            const count = (arms && arms >= 2) ? arms : 3;
            const sp = spread || 0.55;
            const nodes = [makeNode([0, 0, 0], 0, 0.4, 0.12)];
            const edges = [];
            const terminalNodes = [];
            for (let i = 0; i < count; i++) {
                const angle = (2 * Math.PI * i) / count;
                nodes.push(makeNode([Math.cos(angle) * sp, 1, Math.sin(angle) * sp], 0.1, 0.7, 0.07));
                edges.push([0, i + 1]);
                terminalNodes.push(i + 1);
            }
            return { name: "whorl", nodes, edges, rootNode: 0, terminalNodes };
        },
        monopodial: (lateralBranches, lateralSpread) => {
            const lats = lateralBranches || 2;
            const sp = lateralSpread || 0.7;
            const nodes = [makeNode([0, 0, 0], 0, 0.5, 0.15), makeNode([0, 1.2, 0], 0, 1.0, 0.1)];
            const edges = [[0, 1]];
            const terminalNodes = [1];
            for (let i = 0; i < lats; i++) {
                const angle = (2 * Math.PI * i) / lats;
                const idx = nodes.length;
                nodes.push(makeNode([Math.cos(angle) * sp, 0.6 + 0.2 * i, Math.sin(angle) * sp], 0.2, 0.6, 0.06));
                edges.push([0, idx]);
                terminalNodes.push(idx);
            }
            return { name: "monopodial", nodes, edges, rootNode: 0, terminalNodes };
        },
        sympodial: (primarySpread, lateralSpread) => {
            const psp = primarySpread || 0.3;
            const lsp = lateralSpread || 0.7;
            return {
                name: "sympodial",
                nodes: [
                    makeNode([0, 0, 0], 0, 0.5, 0.15),
                    makeNode([0, 0.5, 0], 0, 0.5, 0.12),
                    makeNode([psp, 1.2, 0], 0.1, 0.9, 0.09),
                    makeNode([-lsp, 1.0, 0], 0.2, 0.7, 0.07),
                ],
                edges: [[0, 1], [1, 2], [1, 3]],
                rootNode: 0,
                terminalNodes: [2, 3],
            };
        },
        horizontalTier: (arms, spread) => {
            const count = (arms && arms >= 2) ? arms : 3;
            const sp = spread || 0.85;
            const nodes = [makeNode([0, 0, 0], 0, 0.5, 0.15), makeNode([0, 1.0, 0], 0, 0.8, 0.1)];
            const edges = [[0, 1]];
            const terminalNodes = [1];
            for (let i = 0; i < count; i++) {
                const angle = (2 * Math.PI * i) / count;
                const idx = nodes.length;
                nodes.push(makeNode([Math.cos(angle) * sp, 0.5, Math.sin(angle) * sp], 0.15, 0.7, 0.06));
                edges.push([0, idx]);
                terminalNodes.push(idx);
            }
            return { name: "tier", nodes, edges, rootNode: 0, terminalNodes };
        },
        tier: (arms, spread) => {
            const count = (arms && arms >= 2) ? arms : 3;
            const sp = spread || 0.85;
            const nodes = [makeNode([0, 0, 0], 0, 0.5, 0.15), makeNode([0, 1.0, 0], 0, 0.8, 0.1)];
            const edges = [[0, 1]];
            const terminalNodes = [1];
            for (let i = 0; i < count; i++) {
                const angle = (2 * Math.PI * i) / count;
                const idx = nodes.length;
                nodes.push(makeNode([Math.cos(angle) * sp, 0.5, Math.sin(angle) * sp], 0.15, 0.7, 0.06));
                edges.push([0, idx]);
                terminalNodes.push(idx);
            }
            return { name: "tier", nodes, edges, rootNode: 0, terminalNodes };
        },
        weeping: (spread, droop) => {
            const sp = spread || 0.6;
            const dr = droop || 0.4;
            return {
                name: "weeping",
                nodes: [
                    makeNode([0, 0, 0], 0, 0.5, 0.15),
                    makeNode([0, 0.8, 0], 0, 0.6, 0.11),
                    makeNode([sp, 0.8 - dr, 0], 0.2, 0.8, 0.06),
                    makeNode([-sp, 0.8 - dr, 0], 0.2, 0.8, 0.06),
                ],
                edges: [[0, 1], [1, 2], [1, 3]],
                rootNode: 0,
                terminalNodes: [2, 3],
            };
        },
    });

    // ---- bro.flora.FloraWorld ------------------------------------------------
    function FloraWorld() {
        throw new TypeError("bro.flora.FloraWorld is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.flora.FloraWorldProto;
        if (proto !== undefined) {
            Object.setPrototypeOf(proto, FloraWorld.prototype);
        }
    }
    fn(mount(bro, "flora"), "FloraWorld", FloraWorld);

    fn(FloraWorld.prototype, "addPrototype", function addPrototype(spec) {
        return 0;
    });
    fn(FloraWorld.prototype, "addVoronoiSite", function addVoronoiSite(prototypeIndex, determinacy, apicalControl) {
        if (prototypeIndex === undefined) throw new TypeError("bro.flora.FloraWorld.prototype.addVoronoiSite: prototypeIndex is required");
        return __bro_native.flora.FloraWorld_addVoronoiSite(this, prototypeIndex, determinacy === undefined ? 1 : determinacy, apicalControl === undefined ? 0.5 : apicalControl);
    });
    fn(FloraWorld.prototype, "addPlant", function addPlant(spec) {
        return 0;
    });
    fn(FloraWorld.prototype, "removePlant", function removePlant(plantIdx) {
        if (plantIdx === undefined) throw new TypeError("bro.flora.FloraWorld.prototype.removePlant: plantIdx is required");
        return __bro_native.flora.FloraWorld_removePlant(this, plantIdx);
    });
    fn(FloraWorld.prototype, "step", function step(dt) {
        if (dt === undefined) throw new TypeError("bro.flora.FloraWorld.prototype.step: dt is required");
        return __bro_native.flora.FloraWorld_step(this, dt);
    });
    fn(FloraWorld.prototype, "plantInfo", function plantInfo(plantIdx) {
        return null;
    });
    fn(FloraWorld.prototype, "setClimate", function setClimate(opts) {
        return this;
    });
    fn(FloraWorld.prototype, "sampleShadow", function sampleShadow(pos) {
        return null;
    });
    fn(FloraWorld.prototype, "validate", function validate() {
        return null;
    });
    fn(FloraWorld.prototype, "emitMesh", function emitMesh(sides) {
        return {};
    });
    fn(FloraWorld.prototype, "emitSegments", function emitSegments() {
        return [];
    });
    fn(FloraWorld.prototype, "emitFoliage", function emitFoliage() {
        return [];
    });
    fn(FloraWorld.prototype, "emitBloomAnchors", function emitBloomAnchors() {
        return [];
    });
    fn(FloraWorld.prototype, "emitPlantMesh", function emitPlantMesh(plantIdx, sides) {
        return {};
    });
    fn(FloraWorld.prototype, "emitPlantSegments", function emitPlantSegments(plantIdx) {
        return [];
    });
    fn(FloraWorld.prototype, "emitPlantFoliage", function emitPlantFoliage(plantIdx) {
        return [];
    });
    fn(FloraWorld.prototype, "emitFoliageTransforms", function emitFoliageTransforms(opts) {
        return new Float32Array(0);
    });
    fn(FloraWorld.prototype, "emitSegmentTransforms", function emitSegmentTransforms() {
        return new Float32Array(0);
    });
    fn(FloraWorld.prototype, "emitScatterSegments", function emitScatterSegments(opts) {
        return { segments: new Float32Array(0), segCount: 0 };
    });
    fn(FloraWorld.prototype, "emitBranchTubes", function emitBranchTubes() {
        return { segments: new Float32Array(0), segCount: 0 };
    });

    accessor(FloraWorld.prototype, "simTime",
        function () {
            return __bro_native.flora.FloraWorld_simTime_get(this);
        },
        undefined);
    accessor(FloraWorld.prototype, "plantCount",
        function () {
            return __bro_native.flora.FloraWorld_plantCount_get(this);
        },
        undefined);
    accessor(FloraWorld.prototype, "prototypeCount",
        function () {
            return __bro_native.flora.FloraWorld_prototypeCount_get(this);
        },
        undefined);
    accessor(FloraWorld.prototype, "moduleCount",
        function () {
            return __bro_native.flora.FloraWorld_moduleCount_get(this);
        },
        undefined);
})();
