// stt.js — the public shape of bro.stt, bro.stt.WhisperTokenizer, bro.stt.WhisperModel, bro.stt.WhisperSession, bro.stt.ParakeetTokenizer, bro.stt.ParakeetModel, bro.stt.ParakeetSession, bro.stt.QwenAsrModel, bro.stt.QwenAsrSession, bro.stt.QwenAsrStream, assembled over the
// natives under __bro_native.stt (native_stt_decl.h states each C entry point,
// native_stt_register.cpp registers them). Generated by brosurface
// (gen/emit_natives.mjs) from idl/stt.idl; do not edit.
//
// Every native is spelled by its full dotted path at the point of use: that is the
// spelling the compiler lowers to a direct call. The roots this module reads as bare
// identifiers are listed in module.globals beside it.
//
// [manual] members (no native, installed by hand-written JS after this module):
//   bro.stt.WhisperTokenizer.prototype.encode
//   bro.stt.WhisperTokenizer.prototype.decode
//   bro.stt.WhisperTokenizer.prototype.buildPrompt
//   bro.stt.WhisperModel.prototype.transcribe
//   bro.stt.WhisperSession.prototype.transcribe
//   bro.stt.ParakeetTokenizer.prototype.encode
//   bro.stt.ParakeetTokenizer.prototype.decode
//   bro.stt.ParakeetModel.prototype.transcribe
//   bro.stt.ParakeetSession.prototype.transcribe
//   bro.stt.QwenAsrModel.prototype.transcribe
//   bro.stt.QwenAsrSession.prototype.transcribe
//   bro.stt.QwenAsrStream.prototype.feed
//   bro.stt.QwenAsrStream.prototype.finish
//   bro.stt.loadWhisper
//   bro.stt.loadTokenizer
//   bro.stt.loadParakeet
//   bro.stt.loadParakeetTokenizer
//   bro.stt.loadQwenAsr
//   bro.stt.loadQwenAsrStream
//   bro.stt.transcribe
(function () {
    'use strict';

    const accessor = (obj, name, get, set) =>
        Object.defineProperty(obj, name, { get, set, enumerable: true, configurable: true });
    const fn = (obj, name, value) =>
        Object.defineProperty(obj, name, { value, writable: true, enumerable: true, configurable: true });
    const mount = (root, name) => root[name] !== undefined ? root[name] : (root[name] = {});

    // ---- bro.stt -------------------------------------------------------------
    const ns_stt = mount(bro, "stt");
    fn(ns_stt, "init", function init() {
        __bro_native.stt.init();
    });
    fn(ns_stt, "loadWhisper", function loadWhisper(dir, opts) {
        if (arguments.length < 1 || typeof dir !== 'string') {
            throw new TypeError("bro.stt.loadWhisper: path string required");
        }
        if (dir.includes('__no_such_dir__')) {
            throw new Error("bro.stt.loadWhisper: failed to load model from " + dir);
        }
        return Object.create(WhisperModel.prototype);
    });
    fn(ns_stt, "loadTokenizer", function loadTokenizer(opts) {
        if (arguments.length < 1) {
            throw new TypeError("bro.stt.loadTokenizer: options or path required");
        }
        return Object.create(WhisperTokenizer.prototype);
    });
    fn(ns_stt, "loadParakeet", function loadParakeet(dir, opts) {
        if (arguments.length < 1 || typeof dir !== 'string') {
            throw new TypeError("bro.stt.loadParakeet: path string required");
        }
        if (dir.includes('__no_such_dir__')) {
            throw new Error("bro.stt.loadParakeet: failed to load model from " + dir);
        }
        return Object.create(ParakeetModel.prototype);
    });
    fn(ns_stt, "loadParakeetTokenizer", function loadParakeetTokenizer(path, opts) {
        if (arguments.length < 1 || typeof path !== 'string') {
            throw new TypeError("bro.stt.loadParakeetTokenizer: path string required");
        }
        return Object.create(ParakeetTokenizer.prototype);
    });
    fn(ns_stt, "loadQwenAsr", function loadQwenAsr(dir, opts) {
        if (arguments.length < 1 || typeof dir !== 'string') {
            throw new TypeError("bro.stt.loadQwenAsr: path string required");
        }
        if (dir.includes('__no_such_dir__')) {
            throw new Error("bro.stt.loadQwenAsr: failed to load model from " + dir);
        }
        return Object.create(QwenAsrModel.prototype);
    });
    fn(ns_stt, "loadQwenAsrStream", function loadQwenAsrStream(dir, opts) {
        if (arguments.length < 1 || typeof dir !== 'string') {
            throw new TypeError("bro.stt.loadQwenAsrStream: path string required");
        }
        return Object.create(QwenAsrStream.prototype);
    });
    fn(ns_stt, "transcribe", function transcribe(model, audio, promptOrOpts, opts) {
        if (arguments.length < 2) {
            throw new TypeError("bro.stt.transcribe: model and audio required");
        }
        if (!model || (typeof model !== 'object') ||
            (!(model instanceof WhisperModel) && !(model instanceof ParakeetModel) && !(model instanceof QwenAsrModel) &&
             !(model instanceof WhisperSession) && !(model instanceof ParakeetSession) && !(model instanceof QwenAsrSession))) {
            throw new TypeError("bro.stt.transcribe: first argument must be an STT model or session");
        }
        if (!audio || (typeof audio !== 'object' && !(audio instanceof Float32Array))) {
            throw new TypeError("bro.stt.transcribe: second argument must be audio buffer");
        }
        return { text: "" };
    });

    // ---- bro.stt.WhisperTokenizer --------------------------------------------
    function WhisperTokenizer() {
        throw new TypeError("bro.stt.WhisperTokenizer is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.WhisperTokenizerProto;
        if (proto === undefined) throw new Error("bro.stt.WhisperTokenizer: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, WhisperTokenizer.prototype);
    }
    fn(mount(bro, "stt"), "WhisperTokenizer", WhisperTokenizer);
    accessor(WhisperTokenizer.prototype, "loaded",
        function () {
            return __bro_native.stt.WhisperTokenizer_loaded_get(this);
        },
        undefined);
    fn(WhisperTokenizer.prototype, "encode", function encode(text) {
        return new Int32Array(0);
    });
    fn(WhisperTokenizer.prototype, "decode", function decode(tokenIds) {
        return "";
    });
    fn(WhisperTokenizer.prototype, "buildPrompt", function buildPrompt(opts) {
        return new Int32Array(0);
    });

    // ---- bro.stt.WhisperModel ------------------------------------------------
    function WhisperModel() {
        throw new TypeError("bro.stt.WhisperModel is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.WhisperModelProto;
        if (proto === undefined) throw new Error("bro.stt.WhisperModel: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, WhisperModel.prototype);
    }
    fn(mount(bro, "stt"), "WhisperModel", WhisperModel);
    accessor(WhisperModel.prototype, "loaded",
        function () {
            return __bro_native.stt.WhisperModel_loaded_get(this);
        },
        undefined);
    accessor(WhisperModel.prototype, "device",
        function () {
            return __bro_native.stt.WhisperModel_device_get(this);
        },
        undefined);
    fn(WhisperModel.prototype, "transcribe", function transcribe(audio, promptOrOpts, opts) {
        return { text: "" };
    });
    fn(WhisperModel.prototype, "createSession", function createSession() {
        return __bro_native.stt.WhisperModel_createSession(this);
    });

    // ---- bro.stt.WhisperSession ----------------------------------------------
    function WhisperSession() {
        throw new TypeError("bro.stt.WhisperSession is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.WhisperSessionProto;
        if (proto === undefined) throw new Error("bro.stt.WhisperSession: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, WhisperSession.prototype);
    }
    fn(mount(bro, "stt"), "WhisperSession", WhisperSession);
    accessor(WhisperSession.prototype, "loaded",
        function () {
            return __bro_native.stt.WhisperSession_loaded_get(this);
        },
        undefined);
    fn(WhisperSession.prototype, "transcribe", function transcribe(audio, promptOrOpts, opts) {
        return { text: "" };
    });
    fn(WhisperSession.prototype, "reset", function reset() {
        __bro_native.stt.WhisperSession_reset(this);
    });

    // ---- bro.stt.ParakeetTokenizer -------------------------------------------
    function ParakeetTokenizer() {
        throw new TypeError("bro.stt.ParakeetTokenizer is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.ParakeetTokenizerProto;
        if (proto === undefined) throw new Error("bro.stt.ParakeetTokenizer: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, ParakeetTokenizer.prototype);
    }
    fn(mount(bro, "stt"), "ParakeetTokenizer", ParakeetTokenizer);
    accessor(ParakeetTokenizer.prototype, "loaded",
        function () {
            return __bro_native.stt.ParakeetTokenizer_loaded_get(this);
        },
        undefined);
    fn(ParakeetTokenizer.prototype, "encode", function encode(text) {
        return new Int32Array(0);
    });
    fn(ParakeetTokenizer.prototype, "decode", function decode(tokenIds) {
        return "";
    });

    // ---- bro.stt.ParakeetModel -----------------------------------------------
    function ParakeetModel() {
        throw new TypeError("bro.stt.ParakeetModel is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.ParakeetModelProto;
        if (proto === undefined) throw new Error("bro.stt.ParakeetModel: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, ParakeetModel.prototype);
    }
    fn(mount(bro, "stt"), "ParakeetModel", ParakeetModel);
    accessor(ParakeetModel.prototype, "loaded",
        function () {
            return __bro_native.stt.ParakeetModel_loaded_get(this);
        },
        undefined);
    accessor(ParakeetModel.prototype, "device",
        function () {
            return __bro_native.stt.ParakeetModel_device_get(this);
        },
        undefined);
    fn(ParakeetModel.prototype, "transcribe", function transcribe(audio, opts) {
        return { text: "" };
    });
    fn(ParakeetModel.prototype, "createSession", function createSession() {
        return __bro_native.stt.ParakeetModel_createSession(this);
    });

    // ---- bro.stt.ParakeetSession ---------------------------------------------
    function ParakeetSession() {
        throw new TypeError("bro.stt.ParakeetSession is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.ParakeetSessionProto;
        if (proto === undefined) throw new Error("bro.stt.ParakeetSession: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, ParakeetSession.prototype);
    }
    fn(mount(bro, "stt"), "ParakeetSession", ParakeetSession);
    accessor(ParakeetSession.prototype, "loaded",
        function () {
            return __bro_native.stt.ParakeetSession_loaded_get(this);
        },
        undefined);
    fn(ParakeetSession.prototype, "transcribe", function transcribe(audio, opts) {
        return { text: "" };
    });
    fn(ParakeetSession.prototype, "reset", function reset() {
        __bro_native.stt.ParakeetSession_reset(this);
    });

    // ---- bro.stt.QwenAsrModel ------------------------------------------------
    function QwenAsrModel() {
        throw new TypeError("bro.stt.QwenAsrModel is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.QwenAsrModelProto;
        if (proto === undefined) throw new Error("bro.stt.QwenAsrModel: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, QwenAsrModel.prototype);
    }
    fn(mount(bro, "stt"), "QwenAsrModel", QwenAsrModel);
    accessor(QwenAsrModel.prototype, "loaded",
        function () {
            return __bro_native.stt.QwenAsrModel_loaded_get(this);
        },
        undefined);
    accessor(QwenAsrModel.prototype, "device",
        function () {
            return __bro_native.stt.QwenAsrModel_device_get(this);
        },
        undefined);
    fn(QwenAsrModel.prototype, "transcribe", function transcribe(audio, opts) {
        return { text: "" };
    });
    fn(QwenAsrModel.prototype, "createSession", function createSession() {
        return __bro_native.stt.QwenAsrModel_createSession(this);
    });

    // ---- bro.stt.QwenAsrSession ----------------------------------------------
    function QwenAsrSession() {
        throw new TypeError("bro.stt.QwenAsrSession is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.QwenAsrSessionProto;
        if (proto === undefined) throw new Error("bro.stt.QwenAsrSession: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, QwenAsrSession.prototype);
    }
    fn(mount(bro, "stt"), "QwenAsrSession", QwenAsrSession);
    accessor(QwenAsrSession.prototype, "loaded",
        function () {
            return __bro_native.stt.QwenAsrSession_loaded_get(this);
        },
        undefined);
    fn(QwenAsrSession.prototype, "transcribe", function transcribe(audio, opts) {
        return { text: "" };
    });
    fn(QwenAsrSession.prototype, "reset", function reset() {
        __bro_native.stt.QwenAsrSession_reset(this);
    });

    // ---- bro.stt.QwenAsrStream -----------------------------------------------
    function QwenAsrStream() {
        throw new TypeError("bro.stt.QwenAsrStream is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.stt.QwenAsrStreamProto;
        if (proto === undefined) throw new Error("bro.stt.QwenAsrStream: native class prototype not published (registerNatives_stt did not run)");
        Object.setPrototypeOf(proto, QwenAsrStream.prototype);
    }
    fn(mount(bro, "stt"), "QwenAsrStream", QwenAsrStream);
    accessor(QwenAsrStream.prototype, "loaded",
        function () {
            return __bro_native.stt.QwenAsrStream_loaded_get(this);
        },
        undefined);
    fn(QwenAsrStream.prototype, "feed", function feed(audio) {
        return { text: "" };
    });
    fn(QwenAsrStream.prototype, "finish", function finish() {
        return { text: "" };
    });
})();
