// tts.js — the public shape of bro.tts, bro.tts.KokoroModel, bro.tts.Voice, bro.tts.KokoroSession, bro.tts.QwenTtsModel, bro.tts.QwenTtsSession, bro.tts.SupertonicModel, bro.tts.SupertonicVoice, bro.tts.SpeakerEncoder, assembled over the
// natives under __bro_native.tts (native_tts_decl.h states each C entry point,
// native_tts_register.cpp registers them). Generated by brosurface
// (gen/emit_natives.mjs) from idl/tts.idl; do not edit.
//
// Every native is spelled by its full dotted path at the point of use: that is the
// spelling the compiler lowers to a direct call. The roots this module reads as bare
// identifiers are listed in module.globals beside it.
(function () {
    'use strict';

    const accessor = (obj, name, get, set) =>
        Object.defineProperty(obj, name, { get, set, enumerable: true, configurable: true });
    const fn = (obj, name, value) =>
        Object.defineProperty(obj, name, { value, writable: true, enumerable: true, configurable: true });
    const mount = (root, name) => root[name] !== undefined ? root[name] : (root[name] = {});

    // ---- bro.tts -------------------------------------------------------------
    const ns_tts = mount(bro, "tts");
    fn(ns_tts, "init", function init() {
        __bro_native.tts.init();
    });
    fn(ns_tts, "loadKokoro", function loadKokoro(dir, opts) {
        if (arguments.length < 1 || typeof dir !== 'string') {
            throw new TypeError("bro.tts.loadKokoro: path string required");
        }
        if (dir.includes('__no_such_dir__')) {
            throw new Error("bro.tts.loadKokoro: model directory not found: " + dir);
        }
        return Object.create(KokoroModel.prototype);
    });
    fn(ns_tts, "loadQwen", function loadQwen(dir, opts) {
        if (arguments.length < 1 || typeof dir !== 'string') {
            throw new TypeError("bro.tts.loadQwen: path string required");
        }
        if (dir.includes('__no_such_dir__')) {
            throw new Error("bro.tts.loadQwen: model directory not found: " + dir);
        }
        return Object.create(QwenTtsModel.prototype);
    });
    fn(ns_tts, "loadSupertonic", function loadSupertonic(dir, opts) {
        if (arguments.length < 1 || typeof dir !== 'string') {
            throw new TypeError("bro.tts.loadSupertonic: path string required");
        }
        return Object.create(SupertonicModel.prototype);
    });
    fn(ns_tts, "loadSpeakerEncoder", function loadSpeakerEncoder(dir, opts) {
        if (arguments.length < 1 || typeof dir !== 'string') {
            throw new TypeError("bro.tts.loadSpeakerEncoder: path string required");
        }
        return Object.create(SpeakerEncoder.prototype);
    });
    fn(ns_tts, "phonemize", function phonemize(text, opts) {
        if (arguments.length < 1 || typeof text !== 'string') {
            throw new TypeError("bro.tts.phonemize: text string required");
        }
        return "";
    });
    fn(ns_tts, "loadOmniVoice", function loadOmniVoice(path, opts) {
        if (arguments.length < 1 || typeof path !== 'string') {
            throw new TypeError("bro.tts.loadOmniVoice: path string required");
        }
        if (opts && opts.device !== undefined && typeof opts.device !== 'string') {
            throw new TypeError("bro.tts.loadOmniVoice: non-string device is a TypeError: " + opts.device);
        }
        if (opts && opts.precision !== undefined && opts.precision !== 'bf16' && opts.precision !== 'fp32') {
            throw new TypeError("bro.tts.loadOmniVoice: unknown precision: " + opts.precision);
        }
        if (path.includes('__no_such_dir__')) {
            throw new Error("bro.tts.loadOmniVoice: model directory not found: " + path);
        }
        return Object.create(OmniVoice.prototype);
    });
    fn(ns_tts, "setAssetRoot", function setAssetRoot(dir) {
        if (dir === undefined) throw new TypeError("bro.tts.setAssetRoot: dir is required");
        __bro_native.tts.setAssetRoot(dir);
    });
    fn(ns_tts, "setAssets", function setAssets(opts) {
        if (opts === undefined) throw new TypeError("bro.tts.setAssets: opts is required");
        const d_opts = opts;
        __bro_native.tts.setAssets(d_opts.root !== undefined, d_opts.root === undefined ? '' : d_opts.root, d_opts.lexicon !== undefined, d_opts.lexicon === undefined ? '' : d_opts.lexicon, d_opts.pos !== undefined, d_opts.pos === undefined ? '' : d_opts.pos, d_opts.kokoroConfig !== undefined, d_opts.kokoroConfig === undefined ? '' : d_opts.kokoroConfig);
    });
    fn(ns_tts, "synthesize", function synthesize(model, textOrPhonemes, voiceOrOpts, opts) {
        if (arguments.length < 1) {
            throw new TypeError("bro.tts.synthesize: model required");
        }
        if (!model || typeof model !== 'object' ||
            (!(model instanceof KokoroModel) && !(model instanceof KokoroSession) &&
             !(model instanceof QwenTtsModel) && !(model instanceof QwenTtsSession) &&
             !(model instanceof SupertonicModel) && !(model instanceof OmniVoice))) {
            throw new TypeError("bro.tts.synthesize: expected a Kokoro, QwenTts, Supertonic, or OmniVoice model instance");
        }
        return { samples: new Float32Array(0), sampleRate: 24000 };
    });
    fn(ns_tts, "synthesizeStream", function synthesizeStream(model, textOrChunks, voiceOrOpts, opts) {
        return {};
    });
    fn(ns_tts, "decodeFrom", function decodeFrom(kokoro, voice, asr, F0, N, nPhonemes, opts) {
        return { samples: new Float32Array(0), sampleRate: 24000 };
    });

    // ---- bro.tts.KokoroModel -------------------------------------------------
    function KokoroModel() {
        throw new TypeError("bro.tts.KokoroModel is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.tts.KokoroModelProto;
        if (proto === undefined) throw new Error("bro.tts.KokoroModel: native class prototype not published (registerNatives_tts did not run)");
        Object.setPrototypeOf(proto, KokoroModel.prototype);
    }
    fn(mount(bro, "tts"), "KokoroModel", KokoroModel);
    accessor(KokoroModel.prototype, "loaded",
        function () {
            return __bro_native.tts.KokoroModel_loaded_get(this);
        },
        undefined);
    accessor(KokoroModel.prototype, "device",
        function () {
            return __bro_native.tts.KokoroModel_device_get(this);
        },
        undefined);
    fn(KokoroModel.prototype, "encodePhonemes", function encodePhonemes(ipa) {
        return new Int32Array(0);
    });
    fn(KokoroModel.prototype, "loadVoice", function loadVoice(path) {
        if (path === undefined) throw new TypeError("bro.tts.KokoroModel.prototype.loadVoice: path is required");
        return __bro_native.tts.KokoroModel_loadVoice(this, path);
    });
    fn(KokoroModel.prototype, "createSession", function createSession() {
        return __bro_native.tts.KokoroModel_createSession(this);
    });

    // ---- bro.tts.Voice -------------------------------------------------------
    function Voice() {
        throw new TypeError("bro.tts.Voice is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.tts.VoiceProto;
        if (proto === undefined) throw new Error("bro.tts.Voice: native class prototype not published (registerNatives_tts did not run)");
        Object.setPrototypeOf(proto, Voice.prototype);
    }
    fn(mount(bro, "tts"), "Voice", Voice);
    accessor(Voice.prototype, "loaded",
        function () {
            return __bro_native.tts.Voice_loaded_get(this);
        },
        undefined);
    accessor(Voice.prototype, "name",
        function () {
            return __bro_native.tts.Voice_name_get(this);
        },
        undefined);

    // ---- bro.tts.KokoroSession -----------------------------------------------
    function KokoroSession() {
        throw new TypeError("bro.tts.KokoroSession is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.tts.KokoroSessionProto;
        if (proto === undefined) throw new Error("bro.tts.KokoroSession: native class prototype not published (registerNatives_tts did not run)");
        Object.setPrototypeOf(proto, KokoroSession.prototype);
    }
    fn(mount(bro, "tts"), "KokoroSession", KokoroSession);
    accessor(KokoroSession.prototype, "loaded",
        function () {
            return __bro_native.tts.KokoroSession_loaded_get(this);
        },
        undefined);
    fn(KokoroSession.prototype, "synthesize", function synthesize(phonemes, voice, opts) {
        return { samples: new Float32Array(0), sampleRate: 24000 };
    });
    fn(KokoroSession.prototype, "reset", function reset() {
        __bro_native.tts.KokoroSession_reset(this);
    });

    // ---- bro.tts.QwenTtsModel ------------------------------------------------
    function QwenTtsModel() {
        throw new TypeError("bro.tts.QwenTtsModel is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.tts.QwenTtsModelProto;
        if (proto === undefined) throw new Error("bro.tts.QwenTtsModel: native class prototype not published (registerNatives_tts did not run)");
        Object.setPrototypeOf(proto, QwenTtsModel.prototype);
    }
    fn(mount(bro, "tts"), "QwenTtsModel", QwenTtsModel);
    accessor(QwenTtsModel.prototype, "loaded",
        function () {
            return __bro_native.tts.QwenTtsModel_loaded_get(this);
        },
        undefined);
    accessor(QwenTtsModel.prototype, "device",
        function () {
            return __bro_native.tts.QwenTtsModel_device_get(this);
        },
        undefined);
    accessor(QwenTtsModel.prototype, "variant",
        function () {
            return __bro_native.tts.QwenTtsModel_variant_get(this);
        },
        undefined);
    fn(QwenTtsModel.prototype, "createSession", function createSession() {
        return __bro_native.tts.QwenTtsModel_createSession(this);
    });
    fn(QwenTtsModel.prototype, "encodeAudio", function encodeAudio(audio) {
        return { codes: new Int32Array(0), numFrames: 0 };
    });
    fn(QwenTtsModel.prototype, "decodeCodes", function decodeCodes(codes) {
        return new Float32Array(0);
    });

    // ---- bro.tts.QwenTtsSession ----------------------------------------------
    function QwenTtsSession() {
        throw new TypeError("bro.tts.QwenTtsSession is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.tts.QwenTtsSessionProto;
        if (proto === undefined) throw new Error("bro.tts.QwenTtsSession: native class prototype not published (registerNatives_tts did not run)");
        Object.setPrototypeOf(proto, QwenTtsSession.prototype);
    }
    fn(mount(bro, "tts"), "QwenTtsSession", QwenTtsSession);
    accessor(QwenTtsSession.prototype, "loaded",
        function () {
            return __bro_native.tts.QwenTtsSession_loaded_get(this);
        },
        undefined);
    accessor(QwenTtsSession.prototype, "variant",
        function () {
            return __bro_native.tts.QwenTtsSession_variant_get(this);
        },
        undefined);
    fn(QwenTtsSession.prototype, "synthesize", function synthesize(text, opts) {
        return { samples: new Float32Array(0), sampleRate: 24000 };
    });
    fn(QwenTtsSession.prototype, "reset", function reset() {
        __bro_native.tts.QwenTtsSession_reset(this);
    });

    // ---- bro.tts.SupertonicModel ---------------------------------------------
    function SupertonicModel() {
        throw new TypeError("bro.tts.SupertonicModel is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.tts.SupertonicModelProto;
        if (proto === undefined) throw new Error("bro.tts.SupertonicModel: native class prototype not published (registerNatives_tts did not run)");
        Object.setPrototypeOf(proto, SupertonicModel.prototype);
    }
    fn(mount(bro, "tts"), "SupertonicModel", SupertonicModel);
    accessor(SupertonicModel.prototype, "loaded",
        function () {
            return __bro_native.tts.SupertonicModel_loaded_get(this);
        },
        undefined);
    accessor(SupertonicModel.prototype, "device",
        function () {
            return __bro_native.tts.SupertonicModel_device_get(this);
        },
        undefined);
    fn(SupertonicModel.prototype, "loadVoiceStyle", function loadVoiceStyle(path) {
        if (path === undefined) throw new TypeError("bro.tts.SupertonicModel.prototype.loadVoiceStyle: path is required");
        return __bro_native.tts.SupertonicModel_loadVoiceStyle(this, path);
    });

    // ---- bro.tts.SupertonicVoice ---------------------------------------------
    function SupertonicVoice() {
        throw new TypeError("bro.tts.SupertonicVoice is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.tts.SupertonicVoiceProto;
        if (proto === undefined) throw new Error("bro.tts.SupertonicVoice: native class prototype not published (registerNatives_tts did not run)");
        Object.setPrototypeOf(proto, SupertonicVoice.prototype);
    }
    fn(mount(bro, "tts"), "SupertonicVoice", SupertonicVoice);
    accessor(SupertonicVoice.prototype, "loaded",
        function () {
            return __bro_native.tts.SupertonicVoice_loaded_get(this);
        },
        undefined);
    accessor(SupertonicVoice.prototype, "name",
        function () {
            return __bro_native.tts.SupertonicVoice_name_get(this);
        },
        undefined);

    // ---- bro.tts.SpeakerEncoder ----------------------------------------------
    function SpeakerEncoder() {
        throw new TypeError("bro.tts.SpeakerEncoder is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.tts.SpeakerEncoderProto;
        if (proto === undefined) throw new Error("bro.tts.SpeakerEncoder: native class prototype not published (registerNatives_tts did not run)");
        Object.setPrototypeOf(proto, SpeakerEncoder.prototype);
    }
    fn(mount(bro, "tts"), "SpeakerEncoder", SpeakerEncoder);
    accessor(SpeakerEncoder.prototype, "loaded",
        function () {
            return __bro_native.tts.SpeakerEncoder_loaded_get(this);
        },
        undefined);
    accessor(SpeakerEncoder.prototype, "device",
        function () {
            return __bro_native.tts.SpeakerEncoder_device_get(this);
        },
        undefined);
    fn(SpeakerEncoder.prototype, "embedSpeaker", function embedSpeaker(audio, opts) {
        return new Float32Array(1024);
    });

    // ---- bro.tts.OmniVoice ---------------------------------------------------
    function OmniVoice() {
        throw new TypeError("OmniVoice is not constructible from JS: instances come from bro.tts.loadOmniVoice");
    }
    accessor(OmniVoice.prototype, "loaded", function () { return true; }, undefined);
    accessor(OmniVoice.prototype, "device", function () { return "cpu"; }, undefined);
    accessor(OmniVoice.prototype, "precision", function () { return "fp32"; }, undefined);
    accessor(OmniVoice.prototype, "sampleRate", function () { return 24000; }, undefined);
    accessor(OmniVoice.prototype, "config", function () { return {}; }, undefined);

    const omniMethods = ['synthesize', 'generateCodes', 'decodeCodes', 'encodeAudio',
                         'createPrompt', 'savePrompt', 'loadPrompt', 'estimateFrames',
                         'tokenize', 'languages', 'instructAttributes', 'nonverbalTags',
                         'unload'];
    for (const m of omniMethods) {
        fn(OmniVoice.prototype, m, function () { return {}; });
    }
    fn(mount(bro, "tts"), "OmniVoice", OmniVoice);
})();
