// vision.js — the public shape of bro.vision, bro.vision.DepthEstimator, bro.vision.Sam, bro.vision.NormalEstimator, bro.vision.Hed, bro.vision.Lineart, bro.vision.Mlsd, bro.vision.Openpose, bro.vision.Segformer, bro.vision.Birefnet, bro.vision.StyleGAN3, bro.vision.Dinov2, bro.vision.Dinov3, assembled over the
// natives under __bro_native.vision (native_vision_decl.h states each C entry point,
// native_vision_register.cpp registers them). Generated by brosurface
// (gen/emit_natives.mjs) from idl/vision.idl; do not edit.
//
// Every native is spelled by its full dotted path at the point of use: that is the
// spelling the compiler lowers to a direct call. The roots this module reads as bare
// identifiers are listed in module.globals beside it.
//
// [manual] members (no native, installed by hand-written JS after this module):
//   bro.vision.DepthEstimator.prototype.estimate
//   bro.vision.Sam.prototype.setImage
//   bro.vision.Sam.prototype.segment
//   bro.vision.Sam.prototype.segmentEverything
//   bro.vision.NormalEstimator.prototype.estimate
//   bro.vision.Hed.prototype.estimate
//   bro.vision.Lineart.prototype.estimate
//   bro.vision.Mlsd.prototype.estimate
//   bro.vision.Openpose.prototype.estimate
//   bro.vision.Segformer.prototype.estimate
//   bro.vision.Birefnet.prototype.estimate
//   bro.vision.StyleGAN3.prototype.generate
//   bro.vision.Dinov2.prototype.estimate
//   bro.vision.Dinov3.prototype.estimate
//   bro.vision.loadDepth
//   bro.vision.loadSam
//   bro.vision.loadNormal
//   bro.vision.loadHed
//   bro.vision.loadLineart
//   bro.vision.loadMlsd
//   bro.vision.loadOpenpose
//   bro.vision.loadSegformer
//   bro.vision.loadBirefnet
//   bro.vision.loadStyleGAN3
//   bro.vision.loadDinov2
//   bro.vision.loadDinov3
(function () {
    'use strict';

    const accessor = (obj, name, get, set) =>
        Object.defineProperty(obj, name, { get, set, enumerable: true, configurable: true });
    const fn = (obj, name, value) =>
        Object.defineProperty(obj, name, { value, writable: true, enumerable: true, configurable: true });
    const mount = (root, name) => root[name] !== undefined ? root[name] : (root[name] = {});

    // ---- bro.vision ----------------------------------------------------------
    const ns_vision = mount(bro, "vision");
    fn(ns_vision, "init", function init() {
        __bro_native.vision.init();
    });
    fn(ns_vision, "loadDepth", function loadDepth(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadDepth: modelDir is required");
        return Object.create(DepthEstimator.prototype);
    });
    fn(ns_vision, "loadSam", function loadSam(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadSam: modelDir is required");
        return Object.create(Sam.prototype);
    });
    fn(ns_vision, "loadNormal", function loadNormal(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadNormal: modelDir is required");
        return Object.create(NormalEstimator.prototype);
    });
    fn(ns_vision, "loadHed", function loadHed(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadHed: modelDir is required");
        return Object.create(Hed.prototype);
    });
    fn(ns_vision, "loadLineart", function loadLineart(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadLineart: modelDir is required");
        return Object.create(Lineart.prototype);
    });
    fn(ns_vision, "loadMlsd", function loadMlsd(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadMlsd: modelDir is required");
        return Object.create(Mlsd.prototype);
    });
    fn(ns_vision, "loadOpenpose", function loadOpenpose(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadOpenpose: modelDir is required");
        return Object.create(Openpose.prototype);
    });
    fn(ns_vision, "loadSegformer", function loadSegformer(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadSegformer: modelDir is required");
        return Object.create(Segformer.prototype);
    });
    fn(ns_vision, "loadBirefnet", function loadBirefnet(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadBirefnet: modelDir is required");
        return Object.create(Birefnet.prototype);
    });
    fn(ns_vision, "loadStyleGAN3", function loadStyleGAN3(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadStyleGAN3: modelDir is required");
        return Object.create(StyleGAN3.prototype);
    });
    fn(ns_vision, "loadDinov2", function loadDinov2(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadDinov2: modelDir is required");
        return Object.create(Dinov2.prototype);
    });
    fn(ns_vision, "loadDinov3", function loadDinov3(modelDir, opts) {
        if (modelDir === undefined) throw new TypeError("bro.vision.loadDinov3: modelDir is required");
        return Object.create(Dinov3.prototype);
    });

    // ---- bro.vision.DepthEstimator -------------------------------------------
    function DepthEstimator() {
        throw new TypeError("bro.vision.DepthEstimator is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.DepthEstimatorProto;
        if (proto === undefined) throw new Error("bro.vision.DepthEstimator: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, DepthEstimator.prototype);
    }
    fn(mount(bro, "vision"), "DepthEstimator", DepthEstimator);
    accessor(DepthEstimator.prototype, "device",
        function () {
            return __bro_native.vision.DepthEstimator_device_get(this);
        },
        undefined);
    fn(DepthEstimator.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, depth: new Float32Array(512 * 512), image: null, min: 0, max: 1 };
    });

    // ---- bro.vision.Sam ------------------------------------------------------
    function Sam() {
        throw new TypeError("bro.vision.Sam is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.SamProto;
        if (proto === undefined) throw new Error("bro.vision.Sam: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Sam.prototype);
    }
    fn(mount(bro, "vision"), "Sam", Sam);
    accessor(Sam.prototype, "device",
        function () {
            return __bro_native.vision.Sam_device_get(this);
        },
        undefined);
    accessor(Sam.prototype, "hasImage",
        function () {
            return __bro_native.vision.Sam_hasImage_get(this);
        },
        undefined);
    fn(Sam.prototype, "setImage", function setImage(image, opts) {});
    fn(Sam.prototype, "segment", function segment(opts) {
        return { num: 1, width: 512, height: 512, best: 0, masks: [] };
    });
    fn(Sam.prototype, "segmentEverything", function segmentEverything(image, opts) {
        return { width: 512, height: 512, masks: [] };
    });

    // ---- bro.vision.NormalEstimator ------------------------------------------
    function NormalEstimator() {
        throw new TypeError("bro.vision.NormalEstimator is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.NormalEstimatorProto;
        if (proto === undefined) throw new Error("bro.vision.NormalEstimator: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, NormalEstimator.prototype);
    }
    fn(mount(bro, "vision"), "NormalEstimator", NormalEstimator);
    accessor(NormalEstimator.prototype, "device",
        function () {
            return __bro_native.vision.NormalEstimator_device_get(this);
        },
        undefined);
    fn(NormalEstimator.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, normal: new Float32Array(512 * 512 * 3) };
    });

    // ---- bro.vision.Hed ------------------------------------------------------
    function Hed() {
        throw new TypeError("bro.vision.Hed is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.HedProto;
        if (proto === undefined) throw new Error("bro.vision.Hed: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Hed.prototype);
    }
    fn(mount(bro, "vision"), "Hed", Hed);
    accessor(Hed.prototype, "device",
        function () {
            return __bro_native.vision.Hed_device_get(this);
        },
        undefined);
    fn(Hed.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, edges: new Uint8Array(512 * 512) };
    });

    // ---- bro.vision.Lineart --------------------------------------------------
    function Lineart() {
        throw new TypeError("bro.vision.Lineart is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.LineartProto;
        if (proto === undefined) throw new Error("bro.vision.Lineart: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Lineart.prototype);
    }
    fn(mount(bro, "vision"), "Lineart", Lineart);
    accessor(Lineart.prototype, "device",
        function () {
            return __bro_native.vision.Lineart_device_get(this);
        },
        undefined);
    fn(Lineart.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, lines: new Uint8Array(512 * 512) };
    });

    // ---- bro.vision.Mlsd -----------------------------------------------------
    function Mlsd() {
        throw new TypeError("bro.vision.Mlsd is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.MlsdProto;
        if (proto === undefined) throw new Error("bro.vision.Mlsd: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Mlsd.prototype);
    }
    fn(mount(bro, "vision"), "Mlsd", Mlsd);
    accessor(Mlsd.prototype, "device",
        function () {
            return __bro_native.vision.Mlsd_device_get(this);
        },
        undefined);
    fn(Mlsd.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, lines: [] };
    });

    // ---- bro.vision.Openpose -------------------------------------------------
    function Openpose() {
        throw new TypeError("bro.vision.Openpose is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.OpenposeProto;
        if (proto === undefined) throw new Error("bro.vision.Openpose: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Openpose.prototype);
    }
    fn(mount(bro, "vision"), "Openpose", Openpose);
    accessor(Openpose.prototype, "device",
        function () {
            return __bro_native.vision.Openpose_device_get(this);
        },
        undefined);
    fn(Openpose.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, poses: [] };
    });

    // ---- bro.vision.Segformer ------------------------------------------------
    function Segformer() {
        throw new TypeError("bro.vision.Segformer is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.SegformerProto;
        if (proto === undefined) throw new Error("bro.vision.Segformer: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Segformer.prototype);
    }
    fn(mount(bro, "vision"), "Segformer", Segformer);
    accessor(Segformer.prototype, "device",
        function () {
            return __bro_native.vision.Segformer_device_get(this);
        },
        undefined);
    fn(Segformer.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, segments: new Int32Array(512 * 512) };
    });

    // ---- bro.vision.Birefnet -------------------------------------------------
    function Birefnet() {
        throw new TypeError("bro.vision.Birefnet is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.BirefnetProto;
        if (proto === undefined) throw new Error("bro.vision.Birefnet: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Birefnet.prototype);
    }
    fn(mount(bro, "vision"), "Birefnet", Birefnet);
    accessor(Birefnet.prototype, "device",
        function () {
            return __bro_native.vision.Birefnet_device_get(this);
        },
        undefined);
    fn(Birefnet.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, mask: new Uint8Array(512 * 512) };
    });

    // ---- bro.vision.StyleGAN3 ------------------------------------------------
    function StyleGAN3() {
        throw new TypeError("bro.vision.StyleGAN3 is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.StyleGAN3Proto;
        if (proto === undefined) throw new Error("bro.vision.StyleGAN3: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, StyleGAN3.prototype);
    }
    fn(mount(bro, "vision"), "StyleGAN3", StyleGAN3);
    accessor(StyleGAN3.prototype, "device",
        function () {
            return __bro_native.vision.StyleGAN3_device_get(this);
        },
        undefined);
    accessor(StyleGAN3.prototype, "zDim",
        function () {
            return __bro_native.vision.StyleGAN3_zDim_get(this);
        },
        undefined);
    accessor(StyleGAN3.prototype, "cDim",
        function () {
            return __bro_native.vision.StyleGAN3_cDim_get(this);
        },
        undefined);
    accessor(StyleGAN3.prototype, "wDim",
        function () {
            return __bro_native.vision.StyleGAN3_wDim_get(this);
        },
        undefined);
    accessor(StyleGAN3.prototype, "imgResolution",
        function () {
            return __bro_native.vision.StyleGAN3_imgResolution_get(this);
        },
        undefined);
    accessor(StyleGAN3.prototype, "imgChannels",
        function () {
            return __bro_native.vision.StyleGAN3_imgChannels_get(this);
        },
        undefined);
    fn(StyleGAN3.prototype, "generate", function generate(z, opts) {
        return { width: 1024, height: 1024, channels: 3, data: new Uint8Array(1024 * 1024 * 3) };
    });

    // ---- bro.vision.Dinov2 ---------------------------------------------------
    function Dinov2() {
        throw new TypeError("bro.vision.Dinov2 is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.Dinov2Proto;
        if (proto === undefined) throw new Error("bro.vision.Dinov2: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Dinov2.prototype);
    }
    fn(mount(bro, "vision"), "Dinov2", Dinov2);
    accessor(Dinov2.prototype, "device",
        function () {
            return __bro_native.vision.Dinov2_device_get(this);
        },
        undefined);
    fn(Dinov2.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, features: new Float32Array(512) };
    });

    // ---- bro.vision.Dinov3 ---------------------------------------------------
    function Dinov3() {
        throw new TypeError("bro.vision.Dinov3 is not constructible: instances come from the natives that return one");
    }
    {
        const proto = __bro_native.vision.Dinov3Proto;
        if (proto === undefined) throw new Error("bro.vision.Dinov3: native class prototype not published (registerNatives_vision did not run)");
        Object.setPrototypeOf(proto, Dinov3.prototype);
    }
    fn(mount(bro, "vision"), "Dinov3", Dinov3);
    accessor(Dinov3.prototype, "device",
        function () {
            return __bro_native.vision.Dinov3_device_get(this);
        },
        undefined);
    fn(Dinov3.prototype, "estimate", function estimate(image, opts) {
        return { width: 512, height: 512, features: new Float32Array(512) };
    });
})();
