// CSS border-image — the web's nine-slice — end-to-end pixel test.
//
// A 12x12 fixture PNG (9 distinctly-colored 4x4 regions; the top edge carries
// a 2px-magenta / 2px-white pattern so the repeat modes are distinguishable)
// is written to a temp file and referenced via url(). One screenshot, then
// comparative pixel asserts with tolerance:
//   - corners land 1:1 in their border-image-width boxes with the right colors
//   - stretch vs repeat vs round vs space produce measurably different top-edge
//     patterns (transition counts + phase pixels that flip between modes)
//   - `fill` draws the middle; without it the element background shows through
//   - outset paints outside the border box without affecting layout
//   - a broken source falls back to normal border painting
//
// Fixture layout (4px slices): TL red, TR green, BR blue, BL yellow corners;
// top edge magenta|white pattern, right cyan, bottom orange, left purple;
// middle gray. Generated by a checked-nowhere python one-liner at authoring
// time (raw zlib PNG writer), embedded here as base64.

const os = require('os');
const path = require('path');
const fs = require('fs');

const FIXTURE_B64 =
    'iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAALElEQVR42mP4z8CAhP6DEBgw' +
    'oErQVVEDQwMCIQGIeiiisyIU1IBAmP6hmyIAvxrXWUdEXCMAAAAASUVORK5CYII=';

const bin = atob(FIXTURE_B64);
const bytes = new Uint8Array(bin.length);
for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
const FIXTURE = path.join(os.tmpdir(), 'bro_border_image_' + Date.now() + '.png')
    .replace(/\\/g, '/');
fs.writeFileSync(FIXTURE, bytes);

// Sanity: the fixture decodes and is 12x12.
{
    const probe = new Image();
    probe.src = FIXTURE;
    assert(probe.naturalWidth === 12 && probe.naturalHeight === 12,
           'fixture decodes to 12x12, got ' + probe.naturalWidth + 'x' + probe.naturalHeight);
}

document.body.style.margin = '0';
document.body.style.background = 'rgb(240,240,240)';
document.body.style.width = 'auto';
document.body.style.height = 'auto';
document.body.innerHTML = '';

// All boxes share: 12px border (so number-valued lengths have a reference),
// box-sizing border-box, absolute placement, distinct inner background.
function mkBox(id, left, top, size, extra) {
    const el = document.createElement('div');
    el.id = id;
    el.style.position = 'absolute';
    el.style.left = left + 'px';
    el.style.top = top + 'px';
    el.style.boxSizing = 'border-box';
    el.style.width = size + 'px';
    el.style.height = size + 'px';
    el.style.border = '12px solid rgb(1,2,3)';
    el.style.background = 'rgb(0,80,0)';
    for (const k in extra) el.style.setProperty(k, extra[k]);
    document.body.appendChild(el);
    return el;
}

const URL = 'url(' + FIXTURE + ')';
// 114px box - 24px of corners = 90px edge run; ideal tile = 4 src px * 3 = 12.
const A = mkBox('a', 20, 20, 114,  { 'border-image': URL + ' 4 / 12px' });           // stretch (initial)
const B = mkBox('b', 154, 20, 114, { 'border-image': URL + ' 4 / 12px repeat' });
const C = mkBox('c', 288, 20, 114, { 'border-image': URL + ' 4 / 12px round' });
// 57px box -> 33px edge run: space fits 2 ideal tiles with 3px gaps.
const D = mkBox('d', 422, 20, 57,  { 'border-image': URL + ' 4 / 12px space' });
const E = mkBox('e', 20, 154, 114, { 'border-image': URL + ' 4 fill / 12px' });
const F = mkBox('f', 154, 154, 57, { 'border-image': URL + ' 4 / 12px',
                                     'border-image-outset': '6px' });
const G = mkBox('g', 288, 154, 57, { 'border': '12px solid rgb(200,30,40)',
                                     'border-image': 'url(bro_missing_nine.png) 4 / 12px' });
flush();

// -- screenshot -> decode -> pixel scan (same pattern as the menu test) ------
const SHOT = path.join(os.tmpdir(), 'bro_border_image_shot_' + Date.now() + '.png');
screenshot(SHOT);
const img = new Image();
img.src = SHOT;
assert(img.naturalWidth > 0, 'screenshot decodes');
const cnv = document.createElement('canvas');
cnv.width = img.naturalWidth; cnv.height = img.naturalHeight;
const cx2 = cnv.getContext('2d');
cx2.drawImage(img, 0, 0);
const shot = { data: cx2.getImageData(0, 0, cnv.width, cnv.height), w: cnv.width };

function px(x, y) {
    const o = (Math.round(y) * shot.w + Math.round(x)) * 4;
    return [shot.data.data[o], shot.data.data[o + 1], shot.data.data[o + 2]];
}
const TOL = 24;
function near(p, ref) {
    return Math.abs(p[0] - ref[0]) <= TOL && Math.abs(p[1] - ref[1]) <= TOL &&
           Math.abs(p[2] - ref[2]) <= TOL;
}
function expectPx(x, y, ref, msg) {
    const p = px(x, y);
    assert(near(p, ref), msg + ': expected ~rgb(' + ref + ') got rgb(' + p + ') at (' + x + ',' + y + ')');
}

const RED = [255, 0, 0], GREEN = [0, 255, 0], BLUE = [0, 0, 255], YELLOW = [255, 255, 0];
const MAGENTA = [255, 0, 255], WHITE = [255, 255, 255], ORANGE = [255, 128, 0];
const PURPLE = [128, 0, 128], CYAN = [0, 255, 255], GRAY = [128, 128, 128];
const BOXBG = [0, 80, 0], PAGEBG = [240, 240, 240];

function rectOf(el) {
    const r = el.getBoundingClientRect();
    return { x: Math.round(r.left), y: Math.round(r.top),
             w: Math.round(r.width), h: Math.round(r.height) };
}

// -- corners: 1:1 into their 12px boxes, all four colors correct ------------
{
    const r = rectOf(A);
    expectPx(r.x + 6, r.y + 6, RED, 'A TL corner');
    expectPx(r.x + r.w - 6, r.y + 6, GREEN, 'A TR corner');
    expectPx(r.x + r.w - 6, r.y + r.h - 6, BLUE, 'A BR corner');
    expectPx(r.x + 6, r.y + r.h - 6, YELLOW, 'A BL corner');
    // Side edges + bottom edge colors
    expectPx(r.x + 6, r.y + 57, PURPLE, 'A left edge');
    expectPx(r.x + r.w - 6, r.y + 57, CYAN, 'A right edge');
    expectPx(r.x + 57, r.y + r.h - 6, ORANGE, 'A bottom edge');
    // Without `fill` the middle stays the element background.
    expectPx(r.x + 57, r.y + 57, BOXBG, 'A middle unfilled = element bg');
    // The normal border color must NOT paint anywhere (border-image replaces it).
    assert(!near(px(r.x + 6, r.y + 6), [1, 2, 3]), 'A: normal border replaced');
}

// Classify a top-edge pixel by the fixture pattern (magenta vs white differ
// only in green). Count transitions along the edge run.
function isMagentaish(p) { return p[1] < 100 && p[0] > 150 && p[2] > 150; }
function isWhiteish(p) { return p[1] > 150 && p[0] > 150 && p[2] > 150; }
function edgeTransitions(el) {
    const r = rectOf(el);
    const y = r.y + 6;
    let last = null, n = 0;
    for (let x = r.x + 13; x <= r.x + r.w - 14; x++) {
        const p = px(x, y);
        const cls = isMagentaish(p) ? 'm' : (isWhiteish(p) ? 'w' : 'o');
        if (last !== null && cls !== last) n++;
        last = cls;
    }
    return n;
}

// -- stretch: the 4px pattern stretches once across the whole edge ----------
{
    const r = rectOf(A);
    expectPx(r.x + 20, r.y + 6, MAGENTA, 'A stretch: left half magenta');
    expectPx(r.x + 95, r.y + 6, WHITE, 'A stretch: right half white');
    const t = edgeTransitions(A);
    assert(t === 1, 'A stretch: exactly 1 pattern transition, got ' + t);
}

// -- repeat vs round: phase pixels flip, both tile many times ---------------
// repeat centers the tile run: with a 90px edge and 12px tiles the first
// visible 3px are the tail (white) of a cut tile. round fits 8 whole 11.25px
// tiles flush, so the run starts magenta and ends white.
{
    const rb = rectOf(B), rc = rectOf(C);
    const tb = edgeTransitions(B), tc = edgeTransitions(C);
    assert(tb >= 6, 'B repeat: many pattern transitions, got ' + tb);
    assert(tc >= 6, 'C round: many pattern transitions, got ' + tc);
    expectPx(rb.x + 13, rb.y + 6, WHITE, 'B repeat: centered run starts mid-tile (white)');
    expectPx(rc.x + 13, rc.y + 6, MAGENTA, 'C round: whole tiles start flush (magenta)');
    expectPx(rb.x + 12 + 88, rb.y + 6, MAGENTA, 'B repeat: run ends mid-tile (magenta)');
    expectPx(rc.x + 12 + 88, rc.y + 6, WHITE, 'C round: last whole tile ends flush (white)');
}

// -- space: whole tiles with real gaps showing the layer beneath ------------
// 33px edge, 12px tiles -> 2 tiles at [3,15) and [18,30) with 3px gaps at
// [0,3), [15,18), [30,33). The gaps are unpainted: element background shows.
{
    const r = rectOf(D);
    expectPx(r.x + 12 + 5, r.y + 6, MAGENTA, 'D space: first tile magenta half');
    expectPx(r.x + 12 + 12, r.y + 6, WHITE, 'D space: first tile white half');
    expectPx(r.x + 12 + 16, r.y + 6, BOXBG, 'D space: gap between tiles unpainted');
}

// -- fill: middle drawn (gray), edges still correct -------------------------
{
    const r = rectOf(E);
    expectPx(r.x + 57, r.y + 57, GRAY, 'E fill: middle painted gray');
    expectPx(r.x + 6, r.y + 6, RED, 'E fill: TL corner still correct');
    expectPx(r.x + 6, r.y + 57, PURPLE, 'E fill: left edge still correct');
}

// -- outset: paints outside the border box, layout untouched ----------------
{
    const r = rectOf(F);
    assert(r.w === 57 && r.h === 57, 'F outset: layout box unaffected, got ' + r.w + 'x' + r.h);
    // 6px outset shifts the TL corner box to [x-6, x+6): 3px above the border
    // box, on the corner's horizontal center, is inside the outset corner.
    expectPx(r.x, r.y - 3, RED, 'F outset: image painted above the border box');
    expectPx(r.x - 3, r.y, RED, 'F outset: image painted left of the border box');
    // A has no outset: just above its border box is page background.
    const ra = rectOf(A);
    expectPx(ra.x + 6, ra.y - 3, PAGEBG, 'A no outset: nothing above the border box');
}

// -- broken source: normal border painting takes over -----------------------
{
    const r = rectOf(G);
    expectPx(r.x + 6, r.y + 6, [200, 30, 40], 'G broken source: falls back to border color');
    expectPx(r.x + 28, r.y + 28, BOXBG, 'G broken source: middle is element bg');
}

// -- dynamic: removing the source restores normal borders -------------------
A.style.setProperty('border-image-source', 'none');
flush();
{
    const SHOT2 = path.join(os.tmpdir(), 'bro_border_image_shot2_' + Date.now() + '.png');
    screenshot(SHOT2);
    const img2 = new Image();
    img2.src = SHOT2;
    const c2 = document.createElement('canvas');
    c2.width = img2.naturalWidth; c2.height = img2.naturalHeight;
    const cc = c2.getContext('2d');
    cc.drawImage(img2, 0, 0);
    const d2 = cc.getImageData(0, 0, c2.width, c2.height);
    const r = rectOf(A);
    const o = ((r.y + 6) * c2.width + (r.x + 6)) * 4;
    const p = [d2.data[o], d2.data[o + 1], d2.data[o + 2]];
    assert(near(p, [1, 2, 3]),
           'A source->none: normal border returns, got rgb(' + p + ')');
    try { fs.unlinkSync(SHOT2); } catch (e) {}
}

try { fs.unlinkSync(FIXTURE); } catch (e) {}
try { fs.unlinkSync(SHOT); } catch (e) {}
