// Generates thumbnails/<dir>.png for each app listed in apps.json.
//
// Run from the project root:
//   bro-headless apps/launcher apps/launcher/generate_thumbnails.js
//
// Each app is loaded in a child bro-headless process, given a moment of
// virtual time to settle, then screenshotted into the thumbnails directory.

// Wrapped in an IIFE because the launcher app.js has already declared `fs`,
// `path`, and `cp` at global scope in this same JS context.
(function () {
const fs = require('fs');
const path = require('path');
const cp = require('child_process');

const EXE_DIR = process.env.BRO_EXE_DIR || process.cwd();
const EXE_SUFFIX = process.platform === 'win32' ? '.exe' : '';
const HEADLESS = path.join(EXE_DIR, 'bro-headless' + EXE_SUFFIX);

// Paths resolve via the launcher app's fs base (apps/launcher/).
const manifest = JSON.parse(fs.readFileSync('apps.json', 'utf8'));
const THUMB_DIR = path.join(process.cwd(), 'apps', 'launcher', 'thumbnails');
fs.mkdirSync(THUMB_DIR, { recursive: true });

console.log('bro-headless: ' + HEADLESS);
console.log('thumbnails:   apps/launcher/thumbnails\n');

// brokit's spawnSync doesn't escape embedded quotes when building the shell
// command, which mangles `-e "expr"`. Write the snapshot script to a temp
// .js file per app and pass it as a script path instead.
const TMP_DIR = path.join(process.cwd(), 'apps', 'launcher', 'thumbnails', '.tmp');
fs.mkdirSync(TMP_DIR, { recursive: true });

let failures = 0;
for (const entry of manifest.apps) {
    const dir = entry.dir;
    const appDir = 'apps/' + dir;
    const outAbs = path.join(process.cwd(), 'apps', 'launcher', 'thumbnails',
                             dir + '.png').replace(/\\/g, '/');

    const cfg = (() => {
        try { return JSON.parse(fs.readFileSync('../' + dir + '/bro.json', 'utf8')); }
        catch { return {}; }
    })();
    const width = entry.width || cfg.width || 1280;
    const height = entry.height || cfg.height || 720;

    const scriptPath = path.join(TMP_DIR, `snap_${dir}.js`);
    // Wait long enough for the system splash (≈2.3s animation) to dismiss
    // and for the app's first real frame to render.
    fs.writeFileSync(scriptPath,
        `advanceTime(3000); flush(); screenshot(${JSON.stringify(outAbs)});\n`);

    const r = cp.spawnSync(HEADLESS, [
        '--width', String(width),
        '--height', String(height),
        appDir,
        scriptPath,
    ], { cwd: process.cwd(), timeout: 60_000 });

    const label = `  ${dir.padEnd(16)} → thumbnails/${dir}.png`;
    if (r.status === 0 && fs.existsSync('thumbnails/' + dir + '.png')) {
        console.log(`${label}  ok`);
    } else {
        failures++;
        console.log(`${label}  FAILED (status=${r.status})`);
        if (r.stderr) console.log('stderr: ' + String(r.stderr).slice(-800));
        if (r.stdout) console.log('stdout: ' + String(r.stdout).slice(-400));
        if (r.error)  console.log('error:  ' + r.error.message);
    }
}

// Also emit a static stylesheet mapping each app dir to its thumbnail. The
// launcher links this at page load; dynamically-injected <style> elements
// don't reliably trigger the htmlayout cascade on background-image.
let css = '/* auto-generated by generate_thumbnails.js */\n';
for (const entry of manifest.apps) {
    const dir = entry.dir;
    if (fs.existsSync('thumbnails/' + dir + '.png')) {
        css += `.thumb[data-app="${dir}"] {\n` +
               `  background-image: url(thumbnails/${dir}.png);\n` +
               `}\n`;
    }
}
fs.writeFileSync(path.join(process.cwd(), 'apps', 'launcher', 'thumbnails.css'), css);

console.log(`\n${manifest.apps.length - failures}/${manifest.apps.length} succeeded.`);
process.exit(failures === 0 ? 0 : 1);
})();
