// Flora - procedural plant viewer.
// Archetype selector, age slider, seed, mouse-driven orbit camera.
// Plants are generated by the JS recipes in recipes.js, which compose
// bromesh primitives (spaceColonize, sweep, meshBranches) into per-archetype
// recipes. Per-recipe foliage atlas is supplied in the result.

const canvas = document.getElementById('stage');
const scene = canvas.getContext('scene');

scene.setAmbient([0.05, 0.06, 0.07]);
scene.setToneMap({ mode: 'aces', exposure: 1.0 });

// --- Orbit camera ----------------------------------------------------------
const cam = {
    target: [0, 3, 0],
    theta:  Math.PI * 0.25,   // azimuth around Y
    phi:    Math.PI * 0.30,   // polar from +Y axis (0..PI)
    radius: 14,
    fov:    50,
    near:   0.1,
    far:    400,
};

function applyCamera() {
    const sp = Math.sin(cam.phi), cp = Math.cos(cam.phi);
    const st = Math.sin(cam.theta), ct = Math.cos(cam.theta);
    const eye = [
        cam.target[0] + cam.radius * sp * ct,
        cam.target[1] + cam.radius * cp,
        cam.target[2] + cam.radius * sp * st,
    ];
    scene.setCamera({
        position: eye,
        target:   cam.target,
        up:       [0, 1, 0],
        fov: cam.fov, near: cam.near, far: cam.far,
    });
}
applyCamera();

let dragMode = 0;  // 0 none, 1 orbit, 2 pan
let lastX = 0, lastY = 0;
canvas.addEventListener('mousedown', (e) => {
    lastX = e.clientX; lastY = e.clientY;
    if (e.button === 2 || e.shiftKey) dragMode = 2;
    else if (e.button === 0)          dragMode = 1;
    e.preventDefault();
});
window.addEventListener('mouseup', () => { dragMode = 0; });
canvas.addEventListener('contextmenu', (e) => e.preventDefault());
canvas.addEventListener('mousemove', (e) => {
    if (!dragMode) return;
    const dx = e.clientX - lastX;
    const dy = e.clientY - lastY;
    lastX = e.clientX; lastY = e.clientY;
    if (dragMode === 1) {
        cam.theta += dx * 0.01;
        cam.phi   += dy * 0.01;
        const eps = 0.05;
        if (cam.phi < eps) cam.phi = eps;
        if (cam.phi > Math.PI - eps) cam.phi = Math.PI - eps;
    } else {
        const sp = Math.sin(cam.phi);
        const right = [-Math.sin(cam.theta), 0, Math.cos(cam.theta)];
        const fwd  = [sp * Math.cos(cam.theta), Math.cos(cam.phi), sp * Math.sin(cam.theta)];
        const up = [
            -fwd[1] * right[2],
            right[0] * fwd[2] - right[2] * fwd[0],
            -right[0] * fwd[1],
        ];
        const k = cam.radius * 0.0015;
        cam.target[0] += (-right[0] * dx + up[0] * dy) * k;
        cam.target[1] += (-right[1] * dx + up[1] * dy) * k;
        cam.target[2] += (-right[2] * dx + up[2] * dy) * k;
    }
    applyCamera();
});
canvas.addEventListener('wheel', (e) => {
    const f = Math.exp(e.deltaY * 0.001);
    cam.radius *= f;
    if (cam.radius < 0.5) cam.radius = 0.5;
    if (cam.radius > 500) cam.radius = 500;
    applyCamera();
    e.preventDefault();
}, { passive: false });

// --- Lights & ground -------------------------------------------------------
scene.createLight({
    type: 'directional',
    direction: [-0.4, -0.8, -0.3],
    color: [1.0, 0.97, 0.92],
    intensity: 2.0,
    castsShadow: true,
});

scene.createMesh({
    mesh: 'plane',
    halfW: 10, halfD: 10,
    y: 0,
    color: '#9aa18f',
    metallic: 0.0,
    roughness: 0.95,
    receivesShadow: true,
});

// --- Archetype defaults & dispatch ----------------------------------------

const archetypeDefaults = {
    tree:      { height: 6,   canopyRadius: 3, blobCount: 3 },
    conifer:   { height: 8,   layers: 7, baseCanopyRadius: 2.5 },
    shrub:     { height: 1.5, radius: 1.2, blobCount: 5 },
    grassTuft: { bladeCount: 12, height: 0.4 },
    vine:      { length: 6, radius: 0.04, helixRadius: 0.5, turns: 3 },
    fern:      { leafletPairs: 14, length: 1.5 },
    succulent: { leafCount: 24, leafLength: 0.35 },
};

function buildPlant(archetype, seed, age01) {
    const opts = Object.assign({ seed, age01 }, archetypeDefaults[archetype]);
    return Recipes[archetype](opts);
}

// --- Scene state -----------------------------------------------------------
const archIn  = document.getElementById('archetype');
const ageIn   = document.getElementById('age');
const seedIn  = document.getElementById('seed');
const ageVal  = document.getElementById('ageVal');
const regenBtn = document.getElementById('regen');

let plantNodes = [];

function recreateNodes(result) {
    for (const n of plantNodes) { n.destroy && n.destroy(); }
    plantNodes = [];

    if (!result.parts) return;
    for (const part of result.parts) {
        if (!part.mesh) continue;
        const node = scene.createMesh({
            mesh: part.mesh,
            color: part.color || [0.6, 0.6, 0.6],
            metallic: part.metallic ?? 0.0,
            roughness: part.roughness ?? 0.9,
            castsShadow: true,
            receivesShadow: true,
        });
        plantNodes.push(node);
    }
}

function fitCameraTo(result) {
    const ax = result.aabbMax || [1, 1, 1];
    const an = result.aabbMin || [-1, 0, -1];
    const cx = (ax[0] + an[0]) * 0.5;
    const cy = (ax[1] + an[1]) * 0.5;
    const cz = (ax[2] + an[2]) * 0.5;
    const sx = ax[0] - an[0], sy = ax[1] - an[1], sz = ax[2] - an[2];
    const ext = Math.max(sx, sy, sz);
    cam.target = [cx, cy, cz];
    cam.radius = Math.max(1.0, ext * 2.2);
    applyCamera();
}

function regenerate() {
    const archetype = archIn.value || 'tree';
    const seed = parseInt(seedIn.value, 10) || 1;
    const age  = parseFloat(ageIn.value);
    ageVal.textContent = age.toFixed(2);

    const t0 = performance.now();
    const result = buildPlant(archetype, seed, age);
    const ms = performance.now() - t0;
    const partCount = result.parts ? result.parts.length : 0;
    console.log('regen', archetype, ms.toFixed(2), 'ms,', partCount, 'parts');
    document.getElementById('stats').textContent =
        `${archetype} - ${ms.toFixed(2)} ms - ${partCount} parts`;

    recreateNodes(result);
    return result;
}

const initial = regenerate();
fitCameraTo(initial);

archIn.addEventListener('change', () => {
    const r = regenerate();
    fitCameraTo(r);
});
ageIn.addEventListener('input', regenerate);
seedIn.addEventListener('change', regenerate);
regenBtn.addEventListener('click', regenerate);
