#include "platform/evdev_keymap.h"

namespace bro::platform {

Scancode evdevKeyToScancode(uint32_t key) {
    // Indexed by evdev KEY_* code (linux/input-event-codes.h); 195 .. 255
    // have no counterpart.
    static const Scancode kTable[256] = {
        sc::Unknown,            // 0: KEY_RESERVED
        sc::Escape,             // 1: KEY_ESC
        sc::Digit1,             // 2: KEY_1
        sc::Digit2,             // 3: KEY_2
        sc::Digit3,             // 4: KEY_3
        sc::Digit4,             // 5: KEY_4
        sc::Digit5,             // 6: KEY_5
        sc::Digit6,             // 7: KEY_6
        sc::Digit7,             // 8: KEY_7
        sc::Digit8,             // 9: KEY_8
        sc::Digit9,             // 10: KEY_9
        sc::Digit0,             // 11: KEY_0
        sc::Minus,              // 12: KEY_MINUS
        sc::Equals,             // 13: KEY_EQUAL
        sc::Backspace,          // 14: KEY_BACKSPACE
        sc::Tab,                // 15: KEY_TAB
        sc::Q,                  // 16: KEY_Q
        sc::W,                  // 17: KEY_W
        sc::E,                  // 18: KEY_E
        sc::R,                  // 19: KEY_R
        sc::T,                  // 20: KEY_T
        sc::Y,                  // 21: KEY_Y
        sc::U,                  // 22: KEY_U
        sc::I,                  // 23: KEY_I
        sc::O,                  // 24: KEY_O
        sc::P,                  // 25: KEY_P
        sc::LeftBracket,        // 26: KEY_LEFTBRACE
        sc::RightBracket,       // 27: KEY_RIGHTBRACE
        sc::Return,             // 28: KEY_ENTER
        sc::LCtrl,              // 29: KEY_LEFTCTRL
        sc::A,                  // 30: KEY_A
        sc::S,                  // 31: KEY_S
        sc::D,                  // 32: KEY_D
        sc::F,                  // 33: KEY_F
        sc::G,                  // 34: KEY_G
        sc::H,                  // 35: KEY_H
        sc::J,                  // 36: KEY_J
        sc::K,                  // 37: KEY_K
        sc::L,                  // 38: KEY_L
        sc::Semicolon,          // 39: KEY_SEMICOLON
        sc::Apostrophe,         // 40: KEY_APOSTROPHE
        sc::Grave,              // 41: KEY_GRAVE
        sc::LShift,             // 42: KEY_LEFTSHIFT
        sc::Backslash,          // 43: KEY_BACKSLASH
        sc::Z,                  // 44: KEY_Z
        sc::X,                  // 45: KEY_X
        sc::C,                  // 46: KEY_C
        sc::V,                  // 47: KEY_V
        sc::B,                  // 48: KEY_B
        sc::N,                  // 49: KEY_N
        sc::M,                  // 50: KEY_M
        sc::Comma,              // 51: KEY_COMMA
        sc::Period,             // 52: KEY_DOT
        sc::Slash,              // 53: KEY_SLASH
        sc::RShift,             // 54: KEY_RIGHTSHIFT
        sc::KpMultiply,         // 55: KEY_KPASTERISK
        sc::LAlt,               // 56: KEY_LEFTALT
        sc::Space,              // 57: KEY_SPACE
        sc::CapsLock,           // 58: KEY_CAPSLOCK
        sc::F1,                 // 59: KEY_F1
        sc::F2,                 // 60: KEY_F2
        sc::F3,                 // 61: KEY_F3
        sc::F4,                 // 62: KEY_F4
        sc::F5,                 // 63: KEY_F5
        sc::F6,                 // 64: KEY_F6
        sc::F7,                 // 65: KEY_F7
        sc::F8,                 // 66: KEY_F8
        sc::F9,                 // 67: KEY_F9
        sc::F10,                // 68: KEY_F10
        sc::NumLockClear,       // 69: KEY_NUMLOCK
        sc::ScrollLock,         // 70: KEY_SCROLLLOCK
        sc::Kp7,                // 71: KEY_KP7
        sc::Kp8,                // 72: KEY_KP8
        sc::Kp9,                // 73: KEY_KP9
        sc::KpMinus,            // 74: KEY_KPMINUS
        sc::Kp4,                // 75: KEY_KP4
        sc::Kp5,                // 76: KEY_KP5
        sc::Kp6,                // 77: KEY_KP6
        sc::KpPlus,             // 78: KEY_KPPLUS
        sc::Kp1,                // 79: KEY_KP1
        sc::Kp2,                // 80: KEY_KP2
        sc::Kp3,                // 81: KEY_KP3
        sc::Kp0,                // 82: KEY_KP0
        sc::KpPeriod,           // 83: KEY_KPDOT
        sc::Unknown,            // 84
        sc::Lang5,              // 85: KEY_ZENKAKUHANKAKU
        sc::NonUsBackslash,     // 86: KEY_102ND
        sc::F11,                // 87: KEY_F11
        sc::F12,                // 88: KEY_F12
        sc::International1,     // 89: KEY_RO
        sc::Lang3,              // 90: KEY_KATAKANA
        sc::Lang4,              // 91: KEY_HIRAGANA
        sc::International4,     // 92: KEY_HENKAN
        sc::International2,     // 93: KEY_KATAKANAHIRAGANA
        sc::International5,     // 94: KEY_MUHENKAN
        sc::International5,     // 95: KEY_KPJPCOMMA
        sc::KpEnter,            // 96: KEY_KPENTER
        sc::RCtrl,              // 97: KEY_RIGHTCTRL
        sc::KpDivide,           // 98: KEY_KPSLASH
        sc::SysReq,             // 99: KEY_SYSRQ
        sc::RAlt,               // 100: KEY_RIGHTALT
        sc::Unknown,            // 101: KEY_LINEFEED
        sc::Home,               // 102: KEY_HOME
        sc::Up,                 // 103: KEY_UP
        sc::PageUp,             // 104: KEY_PAGEUP
        sc::Left,               // 105: KEY_LEFT
        sc::Right,              // 106: KEY_RIGHT
        sc::End,                // 107: KEY_END
        sc::Down,               // 108: KEY_DOWN
        sc::PageDown,           // 109: KEY_PAGEDOWN
        sc::Insert,             // 110: KEY_INSERT
        sc::Delete,             // 111: KEY_DELETE
        sc::Unknown,            // 112: KEY_MACRO
        sc::Mute,               // 113: KEY_MUTE
        sc::VolumeDown,         // 114: KEY_VOLUMEDOWN
        sc::VolumeUp,           // 115: KEY_VOLUMEUP
        sc::Power,              // 116: KEY_POWER
        sc::KpEquals,           // 117: KEY_KPEQUAL
        sc::KpPlusMinus,        // 118: KEY_KPPLUSMINUS
        sc::Pause,              // 119: KEY_PAUSE
        sc::Unknown,            // 120: KEY_SCALE
        sc::KpComma,            // 121: KEY_KPCOMMA
        sc::Lang1,              // 122: KEY_HANGEUL
        sc::Lang2,              // 123: KEY_HANJA
        sc::International3,     // 124: KEY_YEN
        sc::LGui,               // 125: KEY_LEFTMETA
        sc::RGui,               // 126: KEY_RIGHTMETA
        sc::Application,        // 127: KEY_COMPOSE
        sc::Stop,               // 128: KEY_STOP
        sc::Again,              // 129: KEY_AGAIN
        sc::AcProperties,       // 130: KEY_PROPS
        sc::Undo,               // 131: KEY_UNDO
        sc::Unknown,            // 132: KEY_FRONT
        sc::Copy,               // 133: KEY_COPY
        sc::AcOpen,             // 134: KEY_OPEN
        sc::Paste,              // 135: KEY_PASTE
        sc::Find,               // 136: KEY_FIND
        sc::Cut,                // 137: KEY_CUT
        sc::Help,               // 138: KEY_HELP
        sc::Menu,               // 139: KEY_MENU
        sc::Unknown,            // 140: KEY_CALC
        sc::Unknown,            // 141: KEY_SETUP
        sc::Sleep,              // 142: KEY_SLEEP
        sc::Wake,               // 143: KEY_WAKEUP
        sc::Unknown,            // 144: KEY_FILE
        sc::Unknown,            // 145: KEY_SENDFILE
        sc::Unknown,            // 146: KEY_DELETEFILE
        sc::Unknown,            // 147: KEY_XFER
        sc::Unknown,            // 148: KEY_PROG1
        sc::Unknown,            // 149: KEY_PROG2
        sc::Unknown,            // 150: KEY_WWW
        sc::Unknown,            // 151: KEY_MSDOS
        sc::Unknown,            // 152: KEY_COFFEE
        sc::Unknown,            // 153: KEY_ROTATE_DISPLAY
        sc::Unknown,            // 154: KEY_CYCLEWINDOWS
        sc::Unknown,            // 155: KEY_MAIL
        sc::AcBookmarks,        // 156: KEY_BOOKMARKS
        sc::Unknown,            // 157: KEY_COMPUTER
        sc::AcBack,             // 158: KEY_BACK
        sc::AcForward,          // 159: KEY_FORWARD
        sc::Unknown,            // 160: KEY_CLOSECD
        sc::MediaEject,         // 161: KEY_EJECTCD
        sc::MediaEject,         // 162: KEY_EJECTCLOSECD
        sc::MediaNextTrack,     // 163: KEY_NEXTSONG
        sc::MediaPlayPause,     // 164: KEY_PLAYPAUSE
        sc::MediaPreviousTrack, // 165: KEY_PREVIOUSSONG
        sc::MediaStop,          // 166: KEY_STOPCD
        sc::MediaRecord,        // 167: KEY_RECORD
        sc::MediaRewind,        // 168: KEY_REWIND
        sc::Unknown,            // 169: KEY_PHONE
        sc::Unknown,            // 170: KEY_ISO
        sc::Unknown,            // 171: KEY_CONFIG
        sc::AcHome,             // 172: KEY_HOMEPAGE
        sc::AcRefresh,          // 173: KEY_REFRESH
        sc::AcExit,             // 174: KEY_EXIT
        sc::Unknown,            // 175: KEY_MOVE
        sc::Unknown,            // 176: KEY_EDIT
        sc::Unknown,            // 177: KEY_SCROLLUP
        sc::Unknown,            // 178: KEY_SCROLLDOWN
        sc::KpLeftParen,        // 179: KEY_KPLEFTPAREN
        sc::KpRightParen,       // 180: KEY_KPRIGHTPAREN
        sc::AcNew,              // 181: KEY_NEW
        sc::Again,              // 182: KEY_REDO
        sc::F13,                // 183: KEY_F13
        sc::F14,                // 184: KEY_F14
        sc::F15,                // 185: KEY_F15
        sc::F16,                // 186: KEY_F16
        sc::F17,                // 187: KEY_F17
        sc::F18,                // 188: KEY_F18
        sc::F19,                // 189: KEY_F19
        sc::F20,                // 190: KEY_F20
        sc::F21,                // 191: KEY_F21
        sc::F22,                // 192: KEY_F22
        sc::F23,                // 193: KEY_F23
        sc::F24,                // 194: KEY_F24
    };
    if (key < 256) return kTable[key];
    return sc::Unknown;
}

int evdevButtonToMouseButton(uint32_t button) {
    switch (button) {
        case kEvdevBtnRight: return 3;
        case kEvdevBtnMiddle: return 2;
        case kEvdevBtnSide: return 4;
        case kEvdevBtnExtra: return 5;
        default: return 1;
    }
}

}  // namespace bro::platform
